### ISSUE TITLE
linter incorrectly reporting interpolation of "shell_escape"

### ISSUE THREAD

**Issue by maxadamo** [puppetlabs/puppet-lint-check_unsafe_interpolations#39]
## Describe the Bug
The linter does not detect the `shell_escape` function, when it's quoted and surrounded by curly brackets.

## Expected Behavior
recognize `shell_escape` as a function and not as a variable to interpolate.

## Steps to Reproduce

I was getting a warning about an unsafe interpolation, I added `shell_escape` as following:
```puppet
command => "/usr/local/bin/vxlan${shell_escape($vxlan_id)}.sh -f -i ${shell_escape($vxlan_id)}",
```
but now I get this different type of warning:
```
WARNING: unsafe interpolation of variable 'shell_escape' in exec command on line 63 (check: check_unsafe_interpolations)
```

## Environment
 - Linter plugin version: 0.0.4
 - Puppet Version: 7.xx
 - Platform Ubuntu 20.04

**Comment by smortex** [comment]
@maxadamo I opened #48 to fix this.  Can you give it a try?
